//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alloclave.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("215, 220, 239")]
        public global::System.Drawing.Color Heap1_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap1_Allocation1"]));
            }
            set {
                this["Heap1_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195, 197, 216")]
        public global::System.Drawing.Color Heap1_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap1_Allocation2"]));
            }
            set {
                this["Heap1_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 237, 216")]
        public global::System.Drawing.Color Heap2_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap2_Allocation1"]));
            }
            set {
                this["Heap2_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("194, 216, 195")]
        public global::System.Drawing.Color Heap2_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap2_Allocation2"]));
            }
            set {
                this["Heap2_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 215, 223")]
        public global::System.Drawing.Color Heap3_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap3_Allocation1"]));
            }
            set {
                this["Heap3_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 183, 195")]
        public global::System.Drawing.Color Heap3_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap3_Allocation2"]));
            }
            set {
                this["Heap3_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242, 220, 195")]
        public global::System.Drawing.Color Heap4_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap4_Allocation1"]));
            }
            set {
                this["Heap4_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 198, 140")]
        public global::System.Drawing.Color Heap4_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap4_Allocation2"]));
            }
            set {
                this["Heap4_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LicenseText {
            get {
                return ((string)(this["LicenseText"]));
            }
            set {
                this["LicenseText"] = value;
            }
        }
    }
}
