//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alloclave.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color Heap1_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap1_Allocation1"]));
            }
            set {
                this["Heap1_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleTurquoise")]
        public global::System.Drawing.Color Heap1_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap1_Allocation2"]));
            }
            set {
                this["Heap1_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Heap2_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap2_Allocation1"]));
            }
            set {
                this["Heap2_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color Heap2_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap2_Allocation2"]));
            }
            set {
                this["Heap2_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 255")]
        public global::System.Drawing.Color Heap3_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap3_Allocation1"]));
            }
            set {
                this["Heap3_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color Heap3_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap3_Allocation2"]));
            }
            set {
                this["Heap3_Allocation2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Heap4_Allocation1 {
            get {
                return ((global::System.Drawing.Color)(this["Heap4_Allocation1"]));
            }
            set {
                this["Heap4_Allocation1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color Heap4_Allocation2 {
            get {
                return ((global::System.Drawing.Color)(this["Heap4_Allocation2"]));
            }
            set {
                this["Heap4_Allocation2"] = value;
            }
        }
    }
}
